# Generated by Django 5.0.1 on 2024-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
